# Site settings
title: The Rust Programming Language Blog
description: >
  Words from the Rust team
baseurl: ""
url: "http://blog.rust-lang.org"
logo: "https://www.rust-lang.org/logos/rust-logo-64x64-blk.png"
twitter_username: rustlang
github_username:  rust-lang

# Build settings
highlighter: rouge

root: http://blog.rust-lang.org
