# https://www.getzola.org/documentation/getting-started/configuration/

base_url = "https://blog.rust-lang.org"
compile_sass = true
generate_feeds = true
feed_filenames = ["feed.xml", "releases.json"]
build_search_index = false

[markdown]
bottom_footnotes = true
insert_anchor_links = "left"

[markdown.highlighting]
light_theme = "light-plus"
dark_theme = "dark-plus"
style = "class"

[extra]
# Put all your custom variables here
