# https://www.getzola.org/documentation/getting-started/configuration/

base_url = "https://blog.rust-lang.org"
compile_sass = true
generate_feeds = true
feed_filenames = ["feed.xml", "releases.json"]
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "boron", filename = "styles/syntax-theme-dark.css" },
  { theme = "OneHalfLight", filename = "styles/syntax-theme-light.css" },
]
bottom_footnotes = true
insert_anchor_links = "left"

[extra]
# Put all your custom variables here
